version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    container_name: web_app
    # unicornを使う場合は以下を実行
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    # unicornを使わない場合は以下を実行
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - /var/tmp
      - .:/app

    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  # ====RDSを使う場合は以下をコメントアウト====
    depends_on:
      - db
  
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - '3308:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql:/usr/scripts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
  # =====================================

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - '80:80'
    volumes_from:
      - app