version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    container_name: web_app
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    # unicornを使わない場合は以下を実行する
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - /var/tmp
      - .:/app

    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  # =========AWSではRDSを使うためコメントアウト===========
    # depends_on:
    #   - database
  
  # database:
  #   image: mysql:8.0.34
  #   platform: linux/amd64
  #   container_name: database
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   ports:
  #     - "3308:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: demo
  #     TZ: "Asia/Tokyo"
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql
  #     - ./sql:/usr/scripts
  # =====================================

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes_from:
      - app