version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - database
    working_dir: /app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
  database:
    image: mysql:8.0.34
    platform: linux/amd64
    container_name: database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql:/usr/scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5  

